### ISSUE TITLE
Alethzero or Mix do not open, CPU goes to 100%

### ISSUE THREAD

**Issue by MrChico** [ethereum/webthree-umbrella#79]
Hey. I am running 
`~  eth --version
eth version 1.1.0
eth network protocol version: 61
Client database version: 12041
Build: Linux/g++/int/Release`
with
`-lspci -v`
...
`00:01.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Mullins [Radeon R4/R5 Graphics] (prog-if 00 [VGA controller])
    Subsystem: Lenovo Device 3801
    Flags: bus master, fast devsel, latency 0, IRQ 43
    Memory at e0000000 (64-bit, prefetchable) [size=256M]
    Memory at f0000000 (64-bit, prefetchable) [size=8M]
    I/O ports at 3000 [size=256]
    Memory at f0c00000 (32-bit, non-prefetchable) [size=256K]
    Expansion ROM at f0800000 [disabled] [size=128K]
    Capabilities: <access denied>
    Kernel driver in use: fglrx_pci`
...
I am unable to open Alethzero or Mix. As I run them, nothing happens except my CPU starts going to 100% for the process. Here is a stacktrace dump:

```
 ~ gdb -ex run alethzero
GNU gdb (Ubuntu 7.9-1ubuntu1) 7.9
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from alethzero...(no debugging symbols found)...done.
Starting program: /usr/bin/alethzero 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
^C
Program received signal SIGINT, Interrupt.
0x00007ffff6f1dc95 in __GI___pthread_mutex_lock (
    mutex=0x7ffff7ffd948 <_rtld_global+2312>)
    at ../nptl/pthread_mutex_lock.c:71
71  ../nptl/pthread_mutex_lock.c: No such file or directory.
(gdb) thread apply all bt

Thread 1 (Thread 0x7fffe1cba780 (LWP 24640)):
#0  0x00007ffff6f1dc95 in __GI___pthread_mutex_lock (
    mutex=0x7ffff7ffd948 <_rtld_global+2312>)
    at ../nptl/pthread_mutex_lock.c:71
#1  0x00007ffff7debce5 in tls_get_addr_tail (ti=0x7ffff3923398, 
    dtv=0x7fffe1cbb090, the_map=0x7ffff7e01000) at dl-tls.c:770
#2  0x00007ffff368a0dc in __cxa_get_globals ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff368a009 in std::uncaught_exception() ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff6860f76 in CryptoPP::AlgorithmParametersBase::~AlgorithmParametersBase() () from /usr/lib/libcryptopp.so
#5  0x00007ffff691dffc in CryptoPP::AlgorithmParametersTemplate<int>::~AlgorithmParametersTemplate() () from /usr/lib/libcryptopp.so
#6  0x00007ffff691e02c in CryptoPP::AlgorithmParametersTemplate<int>::~AlgorithmParametersTemplate() () from /usr/lib/libcryptopp.so
#7  0x00007ffff6856bd9 in CryptoPP::member_ptr<CryptoPP::AlgorithmParametersBase>::~member_ptr() () from /usr/lib/libcryptopp.so
#8  0x00007ffff6856c99 in CryptoPP::AlgorithmParameters::~AlgorithmParameters()
    () from /usr/lib/libcryptopp.so
#9  0x00007ffff686e3c7 in CryptoPP::BaseN_Decoder::BaseN_Decoder(int const*, int, CryptoPP::BufferedTransformation*) () from /usr/lib/libcryptopp.so
---Type <return> to continue, or q <return> to quit---
#10 0x00007ffff686e454 in CryptoPP::HexDecoder::HexDecoder(CryptoPP::BufferedTransformation*) () from /usr/lib/libcryptopp.so
#11 0x00007ffff68f4e6e in CryptoPP::EcRecommendedParameters<CryptoPP::ECP>::NewEC() const () from /usr/lib/libcryptopp.so
#12 0x00007ffff68f5cad in CryptoPP::DL_GroupParameters_EC<CryptoPP::ECP>::Initialize(CryptoPP::OID const&) () from /usr/lib/libcryptopp.so
#13 0x000000000053ff13 in dev::crypto::Secp256k1PP::Secp256k1PP() ()
#14 0x00007ffff512b501 in ?? () from /usr/lib/libdevcrypto.so
#15 0x00007ffff7de95ba in call_init (l=<optimized out>, argc=argc@entry=1, 
    argv=argv@entry=0x7fffffffe378, env=env@entry=0x7fffffffe388)
    at dl-init.c:72
#16 0x00007ffff7de96cb in call_init (env=<optimized out>, 
    argv=<optimized out>, argc=<optimized out>, l=<optimized out>)
    at dl-init.c:30
#17 _dl_init (main_map=0x7ffff7ffe188, argc=1, argv=0x7fffffffe378, 
    env=0x7fffffffe388) at dl-init.c:120
#18 0x00007ffff7dd9d0a in _dl_start_user () from /lib64/ld-linux-x86-64.so.2
#19 0x0000000000000001 in ?? ()
#20 0x00007fffffffe73b in ?? ()
#21 0x0000000000000000 in ?? ()
(gdb) 
```

**Comment by arkpar** [comment]
Thanks for reporting, should be working in the next nightly build
